### ISSUE TITLE
Constructor issue with ActivityTestCase

### ISSUE THREAD

**Issue by shiruba** [techatspree/android-marvin#3]
I followed your documentation on http://stand.spree.de/wiki_details_marvin and created a simple test case:

``` java
public class MainActivityTest extends ActivityTestCase {

    public MainActivityTest(Class type) {
        super(MainActivity.class);
    }

    public void testSelectInsuranceTypeBuilding() {
        activity().view().withId(R.id.insuranceTypeBuilding).click();
    }
}
```

The execution crashes with the following message:

```
junit.framework.AssertionFailedError: Class net.shiruba.android.MainActivityTest has no public constructor TestCase(String name) or TestCase()
```

So I tried to change the constructor to

``` java
public MainActivityTest(String type) {
    super(MainActivity.class);
}
```

which does not help either:

```
junit.framework.AssertionFailedError: Exception in constructor: testSelectInsuranceTypeBuilding (java.lang.RuntimeException: Stub!
at android.test.InstrumentationTestCase.<init>(InstrumentationTestCase.java:5)
    at de.akquinet.android.marvin.AndroidTestCase.<init>(AndroidTestCase.java:52)
    at de.akquinet.android.marvin.ActivityTestCase.<init>(ActivityTestCase.java:52)
    at net.shiruba.android.MainActivityTest.<init>(MainActivityTest.java:12)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
```

If I try to use the default constructor, initialization is chained to the InstrumentationTestCase which throws a RunTimeException, because its a stub.

I am using the 1.1.0 Marvin release with Maven. Any help would be appreciated!

**Comment by ebiermann** [comment]
Hello Sascha,

it seems that you are missing the android test classes at runtime. What device are you running the tests on, emulator or real and are you able to run normal android tests (for example by extending ActivityInstrumentationTestCase2)?

Regards,
Enrico

**Comment by ebiermann** [comment]
Closing issue. If the problem still persists, feel free to reopen the issue.

**Comment by egslava** [comment]
Hello!
Please, write the solution of the problem: I have the same issue (but not with marvin). When I try to test activity with help of ActivityInstrumentationTestCase2<EmptyActivity_> I run into this stacktrace:

```
junit.framework.AssertionFailedError: Exception in constructor: test (java.lang.NullPointerException
at android.test.ActivityInstrumentationTestCase2.getActivity(ActivityInstrumentationTestCase2.java:100)
at com.sogemobile.saytv.api.UploadAvatarTest.<init>(UploadAvatarTest.java:22)
at java.lang.reflect.Constructor.constructNative(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
at junit.runner.BaseTestRunner.getTest(BaseTestRunner.java:118)
at android.test.AndroidTestRunner.getTest(AndroidTestRunner.java:148)
at android.test.AndroidTestRunner.setTestClassName(AndroidTestRunner.java:56)
at android.test.suitebuilder.TestSuiteBuilder.addTestClassByName(TestSuiteBuilder.java:80)
at android.test.InstrumentationTestRunner.parseTestClass(InstrumentationTestRunner.java:444)
at android.test.InstrumentationTestRunner.parseTestClasses(InstrumentationTestRunner.java:425)
at android.test.InstrumentationTestRunner.onCreate(InstrumentationTestRunner.java:370)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4382)
at android.app.ActivityThread.access$1300(ActivityThread.java:141)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5039)
at java.lang.reflect.Method.invokeNative(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
at dalvik.system.NativeStart.main(Native Method)
)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:190)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:175)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1661)
```

Please, help me.

**Comment by shiruba** [comment]
I think my project was lacking the android test classes (as stated above). I did not further follow this approach, so I don't know the solution.
